### ISSUE TITLE
Feature request: Add "source" field to AR -> Search, and remove value for Date Paid for unpaid invoices

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#7436] opened 2023-05-30 21:54 UTC
### Version

1.10

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

I wanted to send an account history to a client to sort out invoices that had been paid, with the corresponding "source" column.

We use "Source" to track a check id or approval code when we receive payments. When reconciling accounts with a customer, it's useful to see this source as applied to invoices.

I tried using Cash -> Reports -> Receipts, but it did not pull up useful information.

AR -> Search, entering a customer number, selecting "All" transactions, "Date Paid" field gets close. But there is no option for source, so I do not have a single report that shows all invoices alongside all payments with their source reference.

Also, lines with unpaid invoices are showing the invoice date in the "Date paid" column, even though they are unpaid.

### What should have happened?

It's possible for an invoice to be paid with multiple payments. Ideally there would be a "source" checkbox on the report setup page, which when selected, would group_concat the source fields for all payments against an invoice in a new column in the report. The same behavior should apply to the date paid column, and this column should be blank if there are no payments received against a particular invoice.

**Comment by ehuelsmann** [comment] 2023-05-31 04:52
Duplicate of #5418 ?

**Comment by ehuelsmann** [comment] 2024-02-13 18:15
Yep. Duplicate of #5418 .

**Closed by ehuelsmann** 2024-02-13 18:15 UTC
Labels: duplicate, type:enhancement
