### ISSUE TITLE
SFF#312  Cannot edit saved draft

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1000] opened 2015-11-01 16:42 UTC
https://sourceforge.net/p/ledger-smb/feature-requests/312/
So, can I edit a draft transaction, because, you know, it was not approved
because it was in error? Nope, none of the edits seem to save when I "Save
Draft".

THis looks like a bug

**Comment by einhverfr** [comment] 2015-11-01 19:21
duplicate of #994

**Comment by ehuelsmann** [comment] 2018-03-29 18:27
Not a dupe. We have (still) sightings of this bug. Edited data doesn't get saved when a saved invoice gets saved/updated.

**Comment by sbts** [comment] 2018-03-30 01:54
In particular the invoice screen is an issue here. Especially when wanting to add payments to a saved but not posted invoice.

Perhaps we can....

- make the payments div on an invoice (even a freshly created one) read only
- add a tool button bar at the bottom of the invoice page that has buttons that pops up divs for
  - payment entry
  - refund
  - voiding
  - any other tools we need

Without digging into the code, on the surface that feels doable with little to no impact on the old code part of the app.
A html change would deal with the read only behaviour and that can be done very easily.
The only old code change would be to add the button bar which is effectively html anyway.

All handling of the buttons should be doable as either JS and new code or purely new code

**Comment by ehuelsmann** [comment] 2020-01-12 12:24
Duplicate of #975

**Closed by ehuelsmann** 2020-01-12 12:24 UTC
