### ISSUE TITLE
AP Transaction total after Saved, is negated

### ISSUE THREAD

**Issue by mcr** [ledgersmb/LedgerSMB#620] opened 2015-02-13 19:59 UTC
Please see this screen shot.
This has been an issue through 1.3, but I thought it got fixed.
I think that showing -2403.36 as negative into Accounts Payable is a bit confusing.  
First, it's positive until you post it, and then it's negative.  It's clearly a total of the lines above, and since Accounts Payable is a liability, it should be happy to have a positive amount posted to it.

http://www.sandelman.ca/tmp/mcrcapture/7178.2015-02-13/capture1.png

**Comment by einhverfr** [comment] 2015-03-14 18:04
Was this an AP transaction or a debit memo?

**Comment by mcr** [comment] 2015-03-14 19:51
Chris Travers <notifications@github.com> wrote:
    > Was this an AP transaction or a debit memo?

AP transaction.
Really, it might always be reasonable to show it negative there,
but it should always be negative then.

**Comment by einhverfr** [comment] 2015-03-15 18:29
I expect to have that fixed this week for 1.4.11

**Comment by ehuelsmann** [comment] 2015-08-16 22:22
@einhverfr Don't think you have this fixed yet. Moving it to 1.4.15. I've seen this many times too. I'm not sure it's *not* in transactions though.

**Comment by ehuelsmann** [comment] 2015-08-23 09:59
1.4.15 is big enough as it is, with more to come. Moving this annoyance to the next patch release, hoping to release 1.4.15 by the end of the coming week.

**Comment by ehuelsmann** [comment] 2015-08-30 17:36
Weird thing is: I can't reproduce this on today's tip of 1.4...

But then again, I've not been able to produce the workflow which retains the screen instead of

a. just showing "Draft posted"
b. show a new input screen

**Comment by ehuelsmann** [comment] 2015-08-30 17:45
Could you please add a step-by-step reproduction recipe? I've seen this happen in the past, but can't seem to reproduce now.

**Comment by ehuelsmann** [comment] 2015-09-11 08:42
@mcr I'd like to include this in 1.4.16, but could you please add a step-by-step reproduction recipe? I've seen this happen in the past, but can't seem to reproduce now.

**Comment by ehuelsmann** [comment] 2015-09-20 19:37
Moving to 1.4.17, lacking a reproduction recipe.

@mcr could you please send me/us the repro recipe? If I don't have one, we can't fix it and will need to close the issue. (You're always free to re-open with a repro recipe, of course!)

**Comment by einhverfr** [comment] 2015-10-18 05:10
closing since we can't repro and have no steps to do so.  Please re-open if you can reproduce.

**Closed by einhverfr** 2015-10-18 05:10 UTC
Labels: bug:other, worksforme
