### ISSUE TITLE
Creating a user via setup.pl defaults to a username matching the superuser

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1677] opened 2016-06-27 18:08 UTC
This is bad, as if you forget to change it, the creation silently fails (user exists)
The username and password field should be empty

**Comment by einhverfr** [comment] 2016-07-17 06:49
Hi

I could not reproduce this.  Could you try clearing your form history and try again?

If you can reproduce please re-open with repro steps and browser information, and assign to 1.5-rc1

**Closed by einhverfr** 2016-07-17 06:49 UTC
Labels: bite-sized, blocking, bug:other
