### ISSUE TITLE
Use Sqitch-like management and deployment

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#840] opened 2015-09-17 19:06 UTC
In order to improve on our schema deployment control, we want to use prior work done in this area by other projects, hence our preference for Switch, which supports postgresql and our choice of versioning tools (git/hg).

This item has been discussed on the development mailing list and with @einhverfr and @freelock . 

Next step is to come up with a plan to move from our current Fixes.SQL based system to a fully sqitch managed system.

When we have that, we also need to write an instruction guide on how to use sqitch to add customizations to the LedgerSMB schema.

**Comment by einhverfr** [comment] 2015-11-22 13:34
As an update, apparently Sqitch cannot solve the branching timeline issues so we need to roll our own solution based on something similar.

I want to have the db structure in place for this in beta 3 and remove the Fixes.sql file.  Then we can work on the rest for beta 4.

**Comment by einhverfr** [comment] 2015-11-28 15:52
I would like to put the following table structure if it works:

    CREATE TABLE fixes (
        sha1 text primary key,
        filename text not null,
        stdout text,
        stderr text,
        applied_at timestamp default now()
    );

This also introduces a sort of "application log" for fixes.

**Comment by einhverfr** [comment] 2015-11-29 08:21
I have updated the schema to include file paths and checksums as Erik has suggested as above.  What follows is a fleshed out proposal based on discussion last night.

We can't really use Sqitch as such because we have a branching timeline and therefore we have to implement something similar which allows for this.  What follows is the strategy and timeline.

First, the problems

1.  In general the problem is that the topology of the version tree does not match a real chronological sort and therefore a version topology sort does not properly ensure ordering across the tree.  A version topology sort was my preferred approach because it simplifies management.

2.  A version topology sort does ensure that the complexity of dependency management is contained and the failure cases relatively modest.

So here is the strategy we came up with.

1.  sql/Fixes/ will contain directories specifying the lowest revision that a fix addresses.  Each fix is placed in a directory there.  And by default we apply a version topology sort.

2.  In the event that this is not sufficient, a .meta file may be placed next to the sql file, allowing for a topological sort of a dependency tree when a new script is loaded.  This is separate so the checksum of the original file is not affected. 

I would propose the following possibilities in the meta file:

1.  depends_on, comma-separated list of paths to logical fixes the current one depends on.  This allows us to make sure that a fix is in place. We can then make sure that the paths to the fixes match ones that have been installed before we install this one.

2.  supereded_by provides a single path to a fix that supercedes the current one but may occur earlier in a version topology sort.  In the event that these have occurred out of order, we *must* re-apply the old one.

A final convention we have agreed on is that we need logs of failures as well.  The structure for these will also be in beta 3.  And that the logs for failures will go through one transaction, while updating the fixes table will go through another.

**Closed** 2016-02-22 19:29 UTC
Labels: blocking, enhancement
