### ISSUE TITLE
Db changes for 1.6:  Drop AR/AP unused columns

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1995] opened 2016-08-06 12:26 UTC
Remove unused columns in ap and ar

**Comment by einhverfr** [comment] 2016-08-06 12:39
Dropping these columns in my remove-charts branch.

**Comment by ehuelsmann** [comment] 2016-08-06 12:46
@einhverfr there's another cleanup I'd like. Compare the columns of the `pnl__line` type with those of `balance_line`:

```sql
CREATE TYPE pnl_line AS (
    account_id int,
    account_number text,
    account_description text,
    account_type char,
    account_category char,
    gifi text,
    gifi_description text,
    contra boolean,
    amount numeric,
    heading_path int[]
);
```
vs
```sql
CREATE TYPE balance_sheet_line AS (
    account_id int,
    account_number text,
    account_desc text,
    account_type char,
    account_category char,
    account_contra boolean,
    gifi_accno text,
    gifi_description text,
    balance numeric,
    heading_path int[]
);
```
I think we should consolidate them into one single type; some of the bugs I just resolved with GIFI are caused by the *near* equality between the two.

**Comment by einhverfr** [comment] 2016-08-06 13:05
@ehuelsmann would you mind filing another ticket on that?

The reason is the ar/ap columns are mostly issues with QA requirements in an operational setting, while this is something that will require a little more design.

**Comment by einhverfr** [comment] 2016-08-06 13:05
(I don't mind if you assign to me, just want to keep issues separate when the sort of things I have to watch out for are separate)

**Closed** 2016-08-20 06:45 UTC
Labels: needs-cleanup
