### ISSUE TITLE
1.5 - Sales Invoice parts cannot be added if they contain an uppercase character

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1536] opened 2016-05-15 17:45 UTC
When creating a new sales order, parts are added to the invoice without this being the intention, and attempting to remove them fails.

1. Go to AR -> Sales Invoice
2. Enter part of a customer name in "Customer" and hit enter/update
3. Result: first part (sorted alphabetically by name?) is added as the first line item:
![selection_167](https://cloud.githubusercontent.com/assets/46937/15275766/4d9a86b0-1a89-11e6-84cb-36ae3d442c70.png)
4. Add the service I want to add, using part selector widget. This auto-fills the description.
5. Set price, qty, click Enter.

Result:
![selection_168](https://cloud.githubusercontent.com/assets/46937/15275792/cc20a9a6-1a89-11e6-82ae-62d30bb322a9.png)

... tried all sorts of different sequences here -- removing the first line item first, changing orders, etc.

But bottom line:

- line item for "article sales" always re-appeared
- My "hourly service" parts, 3 different skus, always resulted in "Item not found"
- Back button on "Item not found" screen took me out to the ar transaction search screen, losing the contents of the invoice

**Comment by ehuelsmann** [comment] 2016-05-15 21:39
@freelock Definitely a challenge, but I can't reproduce here at the moment. I hope you have some time tomorrow to go over it together?

**Comment by sbts** [comment] 2016-05-16 07:06
Freelock I think I've seen this myself. 
I had the impression at the time that my test parts etc probably were incorrectly created.
Can we discuss this on irc please. I suspect remote access for ehuelsmann to look at some specifics will assist there

**Comment by ehuelsmann** [comment] 2016-05-17 12:13
works for me, but: the listing also contains overhead and labor, which cause the behaviour you describe. Did you accidentally select overhead?

**Comment by ehuelsmann** [comment] 2016-05-19 08:16
After some discussion on IRC, this is my status regarding the three findings:

 * In my case (1) doesn't happen -- I really have no way to reproduce
 * I can't reproduce this with items which have been entered as parts or services (I can with overhead, but those shouldn't be in the list: #1548 )
 * Once I fix #1548, you shouldn't be able to get to the "Item not found" page anymore: the page won't submit with unknown items.

**Comment by freelock** [comment] 2016-05-21 15:51
Ok. Worked out the 2nd of the 3 issues with @ehuelsmann on IRC: the "lower()" function on the where clause, didn't match my uppercase partnumber.

The 1st issue is triggered by having partsgroups. Will post new issues for that, and the back button issue.

**Comment by freelock** [comment] 2016-05-21 16:11
Created #1581 , #1579 , #1580, #1582 for issues related to this.

Creating a PR to fix the remaining issue on this issue, the case sensitive match.

**Comment by ehuelsmann** [comment] 2016-06-05 20:31
The fix is in master, so while this doesn't seem to have been closed by the commit, closing because of it.

**Closed by ehuelsmann** 2016-06-05 20:31 UTC
Labels: blocking, worksforme
