### ISSUE TITLE
1.5 Cannot create reconciliation

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1942] opened 2016-08-01 00:57 UTC
This must be a recent regression. Go to Cash -> Reconciliation, enter an account, balance, end date, and click Create.

Result:
![selection_246](https://cloud.githubusercontent.com/assets/46937/17280567/2430f994-5747-11e6-995b-ab3e138565c0.png)

I attempted this on two different accounts, same result.

**Comment by ehuelsmann** [comment] 2016-08-01 08:28
@einhverfr would it be possible to have `PGObject::Simple` add the name of the function it's trying to discover?

@ylavoie this seems like a regression from recent reconciliation work? (It worked when you worked on it, last week?)

**Comment by einhverfr** [comment] 2016-08-01 08:34
yeah I will make that change.

@freelock the problem here is probably that you have an extra function with the same name.  Could you cd to sql/modules/test/ and run System.sql and let me know which functions are duplicate?  There is no software "bug" here afaics, but rather we detected an unsupportable state, so the key to finding the problem is to find how we got here.

For any of the duplicate functions you find, could you please run \df on them and post the full results?   That way I can trace where the problem is.  Maybe we can add a db change script that will remove known problem functions and will be re-un when we find/add more?

**Comment by ehuelsmann** [comment] 2016-08-01 08:38
Wondering if we could add a query (@ylavoie had the required query a few
days ago) as a diagnostic to setup.pl. If we get reports like these more
often, it's easy for us to ask for diagnostics.

**Comment by ylavoie** [comment] 2016-08-02 16:13
Do we have columns identically named in that query? If so, returning cannot decide and we must specify.

**Comment by einhverfr** [comment] 2016-08-02 17:14
no, the name of the function is the discovery criteria so duplicate names mean we cannot decide which one to call.

**Comment by ehuelsmann** [comment] 2016-08-02 21:17
This turns out to be a bug in the upgrade of databases: the old definition of the function doesn't get correctly dropped before defining one with different arguments. So, this *is* a bug and because it affects *all* upgrades, I think it's blocking (it's easy to fix anyway).

**Comment by ehuelsmann** [comment] 2016-08-03 09:23
@ylavoie do you have PR with the code to drop the `reconciliation__get_cleared_balance` function with the old parameterset? That's the proper fix here; when we have that, we can close this.

**Comment by ylavoie** [comment] 2016-08-03 10:36
You will have it tonight

**Comment by einhverfr** [comment] 2016-08-06 01:48
@ylavoie 
since it looks like this has stalled, I can do it if you need me to, but just what we normally do in cases like this is drop the function if it exists in the file which loads it.

**Closed** 2016-08-06 20:08 UTC
Labels: blocking, bug:other
