### ISSUE TITLE
Can't Edit Description on Invoice

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#1283] opened 2016-02-02 11:50 UTC
1.4.23 has broken the workflow I use to create invoices. It is no longer possible to edit the description of a sales invoice line.

To replicate:
* Sales->Sales Invoice
* Enter Product/Service Code
* Click Update - default description shows (e.g. 'Transport Services')
* Edit the description to make it more specific (e.g. 'Transport Services - London to Brighton, 2 Feb')
* Click Update

At this point 1.4.23 brings up the "Item Not On File" page.
Previous versions would update the invoice line description.

**Comment by nick-prater** [comment] 2016-02-10 21:23
Workaround: click 'Save' rather than 'Update'

**Comment by einhverfr** [comment] 2016-03-28 07:40
Duplicate of #1373

**Closed by einhverfr** 2016-03-28 07:40 UTC
Labels: bug:other, regression
