### ISSUE TITLE
General ledger Journal Entry not giving error messages

### ISSUE THREAD

**Issue by cricalixwood** [ledgersmb/LedgerSMB#7806] opened 2023-12-11 10:03 UTC
### Version

1.11.5

### What browsers are you seeing the problem on?

Firefox

### What happened?

Select GL/Journal Entry from menu. Enter any txn , leaving date fiels blank (i.e showing yyyy-mm-dd. Hit update. No error message displayed regarding missing date. Similarly if you should enter a debit and credit for one account on the same line, you just get a refreshed screen, with only the Update button. No error message to indicate why.

### What should have happened?

I think you should get an error message when the data does not pass validation.

**Comment by cricalixwood** [comment] 2023-12-11 10:25
More info: the above is with Separation of Duties=NO

**Comment by ehuelsmann** [comment] 2023-12-11 19:36
Not saying this is by design, but it's impossible to block on an unfilled date field: template transactions allow empty date fields.

At the moment, template transactions may be disabled though (not sure).

**Comment by cricalixwood** [comment] 2023-12-11 19:38
If I do the same thing in 1.10.25, I get an error saying invalid date....(in so far as I would usually just hit Post).

**Comment by ehuelsmann** [comment] 2023-12-11 20:25
Yep. On "Post" that makes sense, but because the transaction is incomplete, you're no longer being offered that button.

I'm contemplating how to proceed on this topic: because the transaction isn't complete, the "button-dealing-code" actually doesn't know there's a "Post" or a "Save" action -- the library which governs the "next steps" doesn't release that information...

With respect to dealing with 2 numbers on a single line, this *is* something we can provide feedback for in the transaction screen.

Do you have any ideas on what to do with the date field?

**Comment by cricalixwood** [comment] 2023-12-11 20:38
Not really. It just seems to me that simply refreshing the page, with no messages, and not proceeding to the next step, is unsatisfactory. 

You said that a blank date was acceptable...so why not let it pass validation, and fail on a subsequent Post if the date remains blank?

**Comment by ehuelsmann** [comment] 2023-12-15 19:12
> Not really. It just seems to me that simply refreshing the page, with no messages, and not proceeding to the next step, is unsatisfactory.

Hmm. From the perspective of the workflow, it *is* moving to the next step: it's applying the Update action and returning to the INITIAL state. While doing so, it offers all buttons allowable for the inputs that have been provided. Since the transaction date is missing, that excludes the "Post" button. But I do get the point that this may be counter-intuitive.

> You said that a blank date was acceptable...so why not let it pass validation, and fail on a subsequent Post if the date remains blank?

The bizarre result of doing it this way is that when opening the transaction screen, you'd have a Post button without anything filled in. Although all the fields are there to make Post a valid operation... Needs more thinking.

**Comment by ehuelsmann** [comment] 2023-12-15 19:15
What we need here is a set of criteria when to *not* to show a button and when to show a button, but prevent its action when the button is triggered.

**Comment by cricalixwood** [comment] 2023-12-15 20:05
Agreed. But after the first post, plus New, post is available with just the date filled in...so what's so bad about that?

Roger

⁣Get BlueMail for Android ​

**Closed** 2024-08-01 19:28 UTC
Labels: needs-design, works-as-designed

**Comment by cricalixwood** [comment] 2024-08-01 19:36
Hi Erik. 

That would be fine.

Regards
Riger

⁣Get BlueMail for Android ​
