### ISSUE TITLE
Regression in 1.6: Cannot upload file to entity or ECA

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3803] opened 2018-09-07 16:57 UTC
When attempting to upload a file to either an entity or an ECA, after browsing to the file I get 'An error occured! Action Not Defined: __default'

**Comment by nick-prater** [comment] 2018-09-07 17:01
Duplicate of #3799 - see notes there.

**Comment by ehuelsmann** [comment] 2018-09-16 20:39
Fixed in the 1.6.5 release.

**Closed by ehuelsmann** 2018-09-16 20:39 UTC
