### ISSUE TITLE
Timecards not showing up

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#1774] opened 2016-07-18 23:36 UTC
On latest pull I have not been able to get Timecards to show up.  I do have transaction approval on, and currently they are not showing up in `Timecards->Search`, or `Transaction Approval`.  The closest I managed to get was to get the card to submit, return with same card, and offer a "print" option.  The print displayed, but also displayed an option.  Will attempt to reproduce.

**Comment by JigmeDatse** [comment] 2016-07-18 23:56
This is where I started.  Well not quite, but this is just before things are starting to look "odd" to me.

![save this](https://cloud.githubusercontent.com/assets/66363/16934078/f8bef21e-4d07-11e6-9562-9a42ed3628bf.png)

This is after having clicked on the save.  The print, and options for print seem to come up, but something is not displaying correctly with the "where to print to" or even "format to print".  

![after save](https://cloud.githubusercontent.com/assets/66363/16934088/12bc9fc2-4d08-11e6-9708-e09f412142a2.png)

I then select "PDF" and "Screen" to get this.  Note it says "HTML" and nothing in the "where to print to" field.

![just before print](https://cloud.githubusercontent.com/assets/66363/16934107/3aae9c92-4d08-11e6-8122-206482543eda.png)

After clicking print this is what I get (I have scrolled down a bit).  It looks fine, but we get a displayed error.  I can see if I can get more of that if it helps.  

![after print](https://cloud.githubusercontent.com/assets/66363/16934125/59af776a-4d08-11e6-8540-074ea53028e2.png)

I didn't look too closely at the JavaScript console, but we are getting errors showing up there too.

**Comment by einhverfr** [comment] 2016-07-20 05:22
On top of that it doesn\'t look possible to set things up for timecards.  I am workin gon this one next I think.

**Comment by einhverfr** [comment] 2016-07-21 03:28
For them not showing up in th reports, could you try extending the date fields?  Obviously there is the printing issue that needs to be addressed as well, but if you manually select an end-date, if ti works, then we may have fixed that part.

**Comment by JigmeDatse** [comment] 2016-07-21 05:23
Search is pulling the timecards up.  Without having to set any dates or anything.  This pulled the previous timecards up.

**Comment by JigmeDatse** [comment] 2016-07-21 05:54
Printing and generating sales orders is not working.

**Comment by JigmeDatse** [comment] 2016-07-21 05:54
New issue for each?

**Comment by einhverfr** [comment] 2016-07-21 07:09
I think the timecard workflow issues can all stay here, but certainly generating and printing sales orders should be listed separately.

**Comment by einhverfr** [comment] 2016-07-21 18:32
The reporting issue has been fixed in another ticket (it was a more general problem).  I am working on the printing issue now.

**Comment by einhverfr** [comment] 2016-07-21 18:41
On the printing issue, the problem is that media is not being passed in properly, and not entirely sure why yet.

**Closed** 2016-07-22 06:18 UTC
Labels: blocking, bug:other
