### ISSUE TITLE
Payment Source options missing for AR and AP "Add Transaction"

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#4137] opened 2019-10-01 11:38 UTC
The following issue was reported by @tonka128
It definitely affects 1.6.10

When using Cash => Receipt or Cash => Payment you can select a source type then enter information into the source text field (eg: a check number)

However the following screens don't present the source type drop down (they do present the text box though)
- AR => Add Transaction
- AR => Sales Invoice
- AP => Add Transaction
- AP => Vendor Invoice

**Comment by ehuelsmann** [comment] 2019-10-01 20:11
@sbts it's not a regression, because it was never there. Agreed that it's an inconsistency.

Question is: which way to solve it: remove from the payment screen or added to the transaction screen. It's nothing more than a prefix on the text inserted into the memo field....

**Comment by sbts** [comment] 2020-01-13 18:51
I'd be adding it to all other screens.
It's a good record of how the payment was made, and can greatly assist when tracking mistakes etc
It's especially useful when reconciling takings at the end of a day

**Comment by ehuelsmann** [comment] 2020-01-13 19:18
I've advocated many times to remove it instead: it simply prepend that value to the source code reference. By extension, everybody who wants it can prepend it themselves. I really can't fathom the cases where this field makes the defining difference in resolving mistakes.

**Comment by sbts** [comment] 2020-01-13 19:23
Well, having a predefined set of values such as
CHQ, EFT, CASH can make searching for, sorting, and filtering on payments significantly easier

For example, if you are trying to reconcile takings at the end of a day and find something doesn't balance.
Listing transactions by cheque, eftpos, and cash (especially with separate totals for each) allows significantly easier verification of where an error has occurred.

In some cases it's just a case of incorrectly attributed payments (cash vs eft)
In others it's a typo etc.
The starting point is always to compare eft transactions entered into LSMB against your eft machine's log

**Comment by ehuelsmann** [comment] 2020-01-13 19:34
What we have is `cash`, `check`, `deposit`, `other`. Don't we have reconciliation for the purpose of reconciling external sources with our own accounts?

**Comment by sbts** [comment] 2020-01-13 19:41
reconciliation as we have it isn't what I'd expect to be used on a daily basis to handle takings of a retail business.
Although it probably can be as long as all data entry has been done correctly through the day.
Either way, the "source type" has always been the method I've used when resolving issues during a day's take

This is a common mechanism to use in other packages as well.
Specifically when dealing with retail like scenarios (till's)

**Comment by ehuelsmann** [comment] 2020-01-13 19:50
But... we removed the entire till support...

**Comment by sbts** [comment] 2020-01-13 19:58
Yep, but the basic process still holds.
I actually never used the till support for my purposes anyway

**Comment by ehuelsmann** [comment] 2020-03-14 23:48
@sbts I still don't understand why you have to force the dropdown on everybody when the text of the dropdown is simply prepended to a text field in the database. You can add that prefix yourself too without burdening the rest of the userbase of LedgerSMB, right? Just like selecting the "correct" type of transaction requires discipline, so does manual entry....

**Comment by ehuelsmann** [comment] 2020-03-15 09:26
Given my latest comment on #2320 and the fact that I have to choose between the two, I'm closing this one.

**Closed by ehuelsmann** 2020-03-15 09:26 UTC
Labels: bite-sized
