### ISSUE TITLE
User password change failure

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#3265] opened 2017-11-12 07:25 UTC
Changing Password from Preferences no longer works but returns `Company does not exist` upon clicking the Password Change button.

**Comment by ehuelsmann** [comment] 2017-11-12 09:15
When something like this happens, there's usually more information in the developer tools Network tab. In this case it is:

```
<html><body><h2 class="error">Error!</h2><p><b>Can't locate object method "error" via package "LedgerSMB::DBObject::User" at /srv/ledgersmb/tools/../old/lib/LedgerSMB/DBObject/User.pm line 107.
</b></p><p>dbversion: 1.6, company: 1.6.0-dev</p></body></html>
```

**Comment by sbts** [comment] 2017-11-12 09:27
#3231 is loosely related in so far as the generated error message is completely incorrect

**Comment by ehuelsmann** [comment] 2017-11-12 11:49
I can't reproduce this problem on any of the docker containers between 1.5.7 and 1.5.13.

As indicated, for authorization problems, demo isn't a good reproduction machine.

It does need to be fixed in master for 1.6 though.

**Comment by ylavoie** [comment] 2017-11-12 19:03
I was not in favor to change password on the demo, we should block that. Nevertheless, changing it for the same value gave the same false message, bad company.

**Comment by ehuelsmann** [comment] 2017-12-17 10:22
So far, I have no idea what to do about it, other than closing as "works for me": I can't reproduce...

**Closed by ehuelsmann** 2017-12-17 10:22 UTC
Labels: worksforme

**Comment by nick-prater** [comment] 2017-12-28 19:19
I'm seeing this issue on master.

  * Go to Preferences->Password
  * Enter correct 'old password'
  * Enter new password 'npt1'
  * Enter verify 'npt1'
  * Click 'Change Password'
  * Get message 'Company does not exist'

**Comment by nick-prater** [comment] 2017-12-28 19:23
Clicking 'Change Password' results in a POST to http://localhost:5762/user.pl
This returns a 500 Internal Server Error response with html body including the message `Can't locate object method "error" via package "LedgerSMB::DBObject::User" at /srv/ledgersmb/tools/../old/lib/LedgerSMB/DBObject/User.pm line 107.`
