### ISSUE TITLE
AR-->Reports-->Customer History Not Showing Results

### ISSUE THREAD

**Issue by Bobberty** [ledgersmb/LedgerSMB#4362] opened 2020-01-16 22:29 UTC
After entering several Sales Orders and Sales Invoices, checking Customer history with different filters resulted in no results.

**Comment by ehuelsmann** [comment] 2020-02-01 17:34
There's an important thing about the history search: you get either invoices or orders, depending on the radio button on the third line above the "Include in report" label.

I am getting outcomes, so, maybe your selections were incompatible with the data in your database?

In order to get this issue resolved, could you create a clean company and describe the exact steps you're performing which then result in this unexpected behaviour (so I can replay these events and see where the problem comes from)?

**Comment by ehuelsmann** [comment] 2020-02-01 17:34
Marking this as a duplicate of #4361 ; I know one is for AR and the other for AP, but I've already asserted they concern the same code path.

**Closed by ehuelsmann** 2020-02-01 17:34 UTC
