### ISSUE TITLE
1.5 Grand Total on Cash Voucher screens includes unchecked customers/vendors

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2026] opened 2016-08-07 17:26 UTC
When you use Cash -> Vouchers -> Receipts or Cash -> Vouchers -> Payments, the grand total shows the total of all outstanding invoice amounts.

When you select a customer/vendor and click Update, in previous versions the grand total gets updated to only include the totals across the selected customers/vendors -- but in 1.5, the total also includes the amounts from unselected customers /vendors.

If you apply a partial payment to a vendor/customer, the grand total does adjust to reflect the changes for that vendor, but still includes the totals from unselected customers/vendors.

This in itself is a nuisance, but it might be contributing to #1936.

**Comment by einhverfr** [comment] 2016-08-07 18:05
this is probably due to the fact that it is calculated in js and we keep changing how we have to do this.  Should not be too hard to fix.  But the problem is probably in the front-end.

**Comment by ehuelsmann** [comment] 2016-08-08 08:53
After consulting with @einhverfr, taking

**Comment by ehuelsmann** [comment] 2016-08-10 21:32
Closing, fixed in a84cc74479a07480de256b8fcd418acedb2d91c9.

**Closed by ehuelsmann** 2016-08-10 21:32 UTC
Labels: regression
