### ISSUE TITLE
1.5 Partial invoice from sales order closes sales order and saves shipped amount

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1613] opened 2016-05-30 05:15 UTC
This is another part of our core workflow that no longer works in 1.5.

1. Create a sales order with qty 20 of an item, and save.
2. Re-open the sales order, enter 5 in the "Ship" box and click Sales Invoice.
3. This takes you to a sales invoice screen with appropriate things copied over -- notes, qty, line items, etc. Success! Save/Post/Email.
4. Go back to Order Entry -> Reports -> Sales Orders.

Result - original order is closed, no longer in the default search.

Expected: new copy of order, with qty 15 in the remaining, and original version (qty 20) closed and findable by searching for closed orders, order number/customer.

Result: Only a single closed order, qty 5.

**Comment by einhverfr** [comment] 2016-07-18 04:28
unable to reproduce.  Closing as works for me.  Please re-open if problem persists on latest master.

**Closed by einhverfr** 2016-07-18 04:28 UTC
Labels: blocking, worksforme
