### ISSUE TITLE
Can't Void Sales Invoice

### ISSUE THREAD

**Issue by craigwebster** [ledgersmb/LedgerSMB#1294] opened 2016-02-03 06:36 UTC
Made an error in Sales Invoice (with payments), attempt to Void, throw this error:

Error!

'select cogs__add_for_ar_line(id) FROM invoice WHERE trans_id = ?
ERROR: control reached end of function without RETURN
CONTEXT: PL/pgSQL function cogs__reverse_ar(integer,numeric)
PL/pgSQL function cogs__add_for_ar_line(integer) line 30 at assignment at LedgerSMB/IS.pm line 56.
'

**Comment by ehuelsmann** [comment] 2016-02-03 08:25
Duplicate of #990 This problem only surfaces if you're selling parts and you're trying to reverse an invoice for which the parts weren't purchased yet.

**Comment by craigwebster** [comment] 2016-02-03 17:13
Ah yes, I see. Apologies for not finding the dupe. This brings up an ancillary question: in this case the item being sold is from an agricultural operation where there's no COGS as such. I think the whole Parts/Services data structure has changed significantly since 1.2 -- is it still workable to have a Part with no COGS?

**Comment by einhverfr** [comment] 2016-02-05 08:29
Yes, it is a duplicate.  If you are selling services it also will not happen (or shouldn't happen).

If there are no COGS, set up services instead.  If this is happening with services then we need to prioritize this further.

**Comment by ehuelsmann** [comment] 2016-02-05 12:57
@einhverfr can you put a few pointers in the other issue as to how I can resolve the situation? Basically, we don't want to revert cogs for transactions which didn't have cogs posted in the first place.

**Comment by einhverfr** [comment] 2016-02-05 15:22
If they don't have cogs I think we could allocate them for cogs allocation purposes.  i.e set allocation field.  (allocation is sign inverse to qty, so when allocated + qty = 0, then the row is fully allocated)

**Comment by ehuelsmann** [comment] 2016-02-05 15:29
Hmm, so the reversal invoice should be allocated to the unallocated sales invoice? After all, this problem occurs when reversing an invoice when no actual purchases have been recorded.

**Comment by einhverfr** [comment] 2016-02-05 16:16
I think you can just cross-allocate.
i.e. on one side you will have a qty of 4 and you can set the allocated to -4, while on the other side it is the reverse.

**Comment by ehuelsmann** [comment] 2016-02-05 18:39
Hmm. Ok. Except that we don't know which invoice we're voiding. I'm now adding code which will allocate the "returned" items to the oldest invoice which has "room" for allocation. I the exact case of @craigwebster this would mean exactly the voided invoice; in some cases it won't, but it also means that the fifo queue only kicks in when there's an actual inventory.

**Comment by einhverfr** [comment] 2016-02-05 18:51
I think that is fine

**Comment by einhverfr** [comment] 2016-02-05 18:52
That would preserve FIFO, and so would be best.

**Comment by ehuelsmann** [comment] 2016-02-06 23:23
With #990 closed, this one is fixed as well.

**Closed** 2016-02-06 23:23 UTC
Labels: duplicate
