### ISSUE TITLE
employee record "user tab" should have a "drop role" / "drop user" button

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1687] opened 2016-06-28 10:15 UTC
Currently there is no method to remove a db user / role from within the UI.
We probably should allow this to be done so that mistakes can be corrected, and employees that no-longer should have access to the db can be removed
(the actual employee record will of course not be removed, just the db role that allows them to login)

**Comment by einhverfr** [comment] 2016-07-18 12:20
consolidated with https://sourceforge.net/p/ledger-smb/feature-requests/309/

**Comment by einhverfr** [comment] 2016-07-27 17:54
duplicate of #1135

**Closed by einhverfr** 2016-07-27 17:54 UTC
Labels: enhancement
