### ISSUE TITLE
Doubling line on AR/AP transaction update after save

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5564] opened 2021-06-14 03:46 UTC
Although the save(Save Draft) clear all the unnecessary lines, the 'Update' action on the saved transaction generate double lines.

**Comment by ehuelsmann** [comment] 2021-06-14 17:08
@aungzwin10 is this with master, 1.9 or 1.8? I'm getting consistently correct (non-doubling) behaviour on master and 1.9.

**Comment by aungzwin10** [comment] 2021-06-15 02:09
@ehuelsmann Correct, it doesn't happen on 1.9 and master. This exist in 1.8 and below

**Comment by ehuelsmann** [comment] 2021-06-19 07:14
Ok. In that case, I'm going to conclude that it should be working going forward and that that is the way users can have access to this fix; I'll focus myself on getting our code base off of the old/ code which is actually the cause of this problem.
Compared to some of the other issues that are also open, I think this is an annoyance (although it can be very visible, depending on your workflow). For now, I'll close this as `wontfix` to be able to focus my time. If you disagree, please re-open explaining your reasoning.

**Closed by ehuelsmann** 2021-06-19 07:14 UTC
Labels: wontfix
