### ISSUE TITLE
Notes are not saved when invoices are updated

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2987] opened 2017-07-07 02:09 UTC
In v1.4, when you add a note to an existing invoice and update it, although from the invoice screen, the note appears to have been saved, if you navigate away and back to the invoice, you'll find the note is gone.

Tested in demo of v1.4. I added a note to invoice 1395, update the invoice. The page refreshed, the note was there. I went back to invoice search, searched for 1395, opened it, and the note was gone.

**Comment by sbts** [comment] 2017-07-07 20:02
Update is a little tricky in the terminology.
As this is a web app, and version 1.4 hasn't been fully ported away from a static html design (server side processing, client side static)
the update button simply "updates" the client side with any new data the server can offer based on information that may have been entered by the user.

To actually store the entered information in the database it's necessary to either "save" or "post" depending on the screen (and version of the software)

This is handled much better in 1.5 where we have moved more UI functionality into client side "dojo" widgets, but there is still work to be done. 

I'll close this one as Works for me.
Let us know if this is still an issue for you

**Closed** 2017-07-07 20:06 UTC
Labels: worksforme

**Comment by ehuelsmann** [comment] 2017-07-09 07:04
See #2992 for the UI improvement issue for the lesson learned.

**Comment by funkypenguin** [comment] 2017-07-19 09:18
Noted, thank you :)

**Comment by funkypenguin** [comment] 2017-09-19 01:45
I've retested this, you're correct about the "Update" button, but there does seem to be a fault with the "Notes" field. In 1.4 demo, I added both a note _and_ and "internal note" to Inv 1645, and clicked "Save Info". Only the internal note was saved. Is this intentional (i.e. to limit change after an invoice is posted), or a bug?

**Comment by funkypenguin** [comment] 2017-09-19 01:46
@ehuelsmann sorry, I couldn't re-open this issue myself since I'm not the closer :)

**Comment by ehuelsmann** [comment] 2017-09-19 22:22
@funkypenguin , no problem. The fact that only limited change can be applied to a posted invoice is by design.The internal notes won't be printed on the invoice, but the regular ones will. S the invoice is frozen after posting, the notes fields is frozen, whereas the internal notes are not.

**Comment by funkypenguin** [comment] 2017-09-20 22:27
Hey @ehuelsmann,

Is there a process to "draft" an invoice, which would allow me to adjust line items, notes, etc, export to PDF, and prepare my invoice _before_ I post it?

If I have a 50-line invoice which I need to prepare/tweak, how should I do this so that I can iterate through multiple versions, save as a "draft" and return to it again later to post it?

Thanks :)
D

**Comment by ehuelsmann** [comment] 2017-09-21 21:24
Hi @funkypenguin,

If you turn on "Separate Duties" (on the System > Defaults page), you can save an invoice before posting it.

Regards,

Erik.

**Comment by funkypenguin** [comment] 2017-09-21 22:28
Hey Erik,

I had our primary user test this, and it's not working (described below). Did we do it wrong?

D

> Steps taken:
> 
>     System > Defaults
> 
>         Deselect 'Separate Duties'
>         Save
>         Select 'Separate Duties'
>         Save
> 
>     AR > Sales Invoice
> 
>         Populated line item 1 with inventory goods
>         Entered 'notes' and 'internal notes'
>         Save
> 
>     Transaction Approval > Drafts
> 
>         Opened draft invoice
>         Updated 'notes' and 'internal notes'
>         Updated the description in line item one
>         Post
> 
>     View posted invoice
> 
>         'Notes', 'internal notes' and line item 1 remain as saved in draft in step 2; i.e., none of the changes made in step 3 are visible on posted invoice.

**Comment by funkypenguin** [comment] 2017-10-01 21:09
Hi Erik,

Am I "holding it wrong", or is this a bug? :)

Thanks!
D

**Comment by funkypenguin** [comment] 2017-10-04 21:09
So "apparently" this is now working, after a retest. In the interim, the host has rebooted, meaning postgresql and starman have both restarted. Could this have impacted the behaviour?

Thanks,
D

**Comment by einhverfr** [comment] 2017-10-05 09:09
Starman caches a lot of things, so it is possible that restarting it could force re-reading relevant Perl modules, but I am having a hard time seeing this happen in real life without it noticing.  So not sure.
