### ISSUE TITLE
Can't log in on companies with '&' in name

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1004] opened 2015-11-03 10:30 UTC

**Comment by einhverfr** [comment] 2016-03-29 12:56
I think we have a more general encoding issue here.  I am wondering if we need a more general solution to it.

**Comment by einhverfr** [comment] 2016-07-18 07:10
actually the problem is fairly simple.  Expect to have this fixed in 1.4.31

**Comment by einhverfr** [comment] 2016-07-18 07:47
I have a fix for 1.4
For 1.5 I have the login issues fixed, but db creation is creating dbs named testing&amp;testing which is clearly wrong.....

**Closed** 2016-07-18 09:08 UTC
Labels: bite-sized, bug:other
