### ISSUE TITLE
Default date on new invoice is tomorrow

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#2587] opened 2017-01-27 00:57 UTC
In 1.5.2, when adding a new sales invoice, the date gets set to tomorrow for Invoice Created and Invoice Date. This happens when you go to the create screen automatically, and does not appear to be due to timezone offset from UTC -- we have several invoices created earlier today that we just realized have tomorrow's date on them.

**Comment by ehuelsmann** [comment] 2017-01-30 20:53
The problem here is likely related to localization of dates and times sent by the server and the way Dojo deals with these.

**Comment by ehuelsmann** [comment] 2017-06-14 19:54
Unfortunately, this isn't trivial. The diagnosis is as follows:

The server retrieves the current date/time from the PostgreSQL server through the `current_date`. The server, in @freelock's case is configured to run in UTC. Which means that the server crosses over into a new date way before @freelock does. So much more even that it's still afternoon where @freelock is working. Since the current date is used to propose a posting date, sometime in @freelock's afternoon, the server will start proposing "tomorrow" as the posting date.

**Comment by ehuelsmann** [comment] 2017-06-14 19:57
Moving this back to 1.5: We need some way for the client to indicate what date/time it considers "today", at least until we move more of the responsibilities to the client.

**Comment by ehuelsmann** [comment] 2017-08-16 09:22
Wanted to fix this for 1.5.10, but there's a lot more to this than meets the eye. One thing is for sure: this is unlikely to be "just" a regression. Here's what discussion on the Matrix channel regarding this topic summarizes to:

* Dojo's dijit/form/DateTextBox uses JavaScript's `Date` class (which is in fact a DateTime class), discarding the 'time' part of the object
* When serializing the 'date' part of the `Date` object, the DateTextBox uses the UTC representation (while the presented date seems to be based on the localized date+time)
* The server doesn't have a notion of the client's time or date - let alone timezone - but sets it's own concept of "today" as the default value for the transaction date (`transdate` - an omni-present field, even in Quotations/RFQs and Orders)

With 51 occurrences of the string "current_date" in our sources, this is not something we can solve within the current stable 1.5 release cycle.

**Comment by ehuelsmann** [comment] 2017-12-17 11:27
Another solution could be to have the Dojo widget initialize itself with its own "now" concept by telling it to use a default value when none is provided.

**Comment by ehuelsmann** [comment] 2017-12-17 18:59
High impact if we go with this proposed route. Moving to 1.7 (we can always backport later.)

**Comment by sbts** [comment] 2017-12-18 12:21
I'm thinking we should look closely at
[JavaScript gettimezoneoffset](https://www.w3schools.com/jsref/jsref_gettimezoneoffset.asp)

**Closed** 2019-11-29 22:30 UTC
