### ISSUE TITLE
Cannot import using existing headers into Chart of Accounts using CSV

### ISSUE THREAD

**Issue by lumberjacklv** [ledgersmb/LedgerSMB#8221] opened 2024-05-19 02:25 UTC
### Version

1.11.14

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

When attempting to upload a CSV with Accounts that reference an existing header, the import will fail with an error:

> Unable to resolve heading 5000 to its id; available: at lib/LedgerSMB/Scripts/import_csv.pm line 378

### What should have happened?

I am expecting that I should be able to reference existing Headers that are defined already when creating a Chart of Accounts upload.

**Comment by neilt** [comment] 2024-07-03 16:20
Can you provide a 3 or 4 line example of the CSV file you are trying to import?

**Comment by ehuelsmann** [comment] 2024-08-01 18:46
This is a duplicate of #7853 which includes a work-around export in the form of a query database query.

**Closed by ehuelsmann** 2024-08-01 18:46 UTC
