### ISSUE TITLE
Request for enhancements to CoA listing

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7931] opened 2024-01-17 10:33 UTC
### Version

1.11.8

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

This is from a post I made in the user list last month.
```
1. A system option to abandon the listing of GIFI for those countries who do not use it, or if there are no entries in that field. It's a waste of space if not used.
2. Include in the CoA listing flags for additional items - Account Type, Contra, Reconciliation, Tax, Obsolete, Negative Balance Heading.
3. Tier the presentation of the Description field in the CoA to reflect the structure of the CoA. This could possibly be achieved by means of CSS.
```

### What should have happened?

Priority consideration to the request.

**Comment by ehuelsmann** [comment] 2024-01-19 18:45
Duplicate of #7740

**Closed by ehuelsmann** 2024-01-19 18:45 UTC
Labels: duplicate
