### ISSUE TITLE
Upload logo to db for use in templates

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1933] opened 2016-07-31 17:20 UTC
We also then need a way of telling the user how to use that logo.
There are other subsystems already allowing image upload. See https://vector.im/beta/#/room/!qyoLumPqusaXqFJNyK:matrix.org/%241469985173842029rMLAP:matrix.org for extra info

**Comment by einhverfr** [comment] 2016-07-31 17:43
duplicate of #1816

**Closed by einhverfr** 2016-07-31 17:43 UTC
