### ISSUE TITLE
Invoice entry "part Description" search incorrectly selects first unfiltered part by default

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3267] opened 2017-11-12 12:13 UTC
if you type a partial (or complete) item description, the dropdown filter displays matches which is good.
However, if there is only a single match, hitting enter results in the first unfiltered "partnumber" to be selected and used.

Even for a single match, it's necessary to select an item from the filtered list!

This breaks clean workflow when compared to older versions.
Certainly in 1.2 it was possible to enter a partial string and have it match a single item without showing/interacting with a list

This is a related, but inverted issue to #3266

**Comment by ehuelsmann** [comment] 2017-11-17 20:49
What does this block?

**Comment by sbts** [comment] 2017-11-18 03:27
Good question actually.
IMNSHO it blocks due to the fact that it makes it EXTREMELY easy to end up with an unexpected part used.
Especially if the operator is used to the common workflow of "enter a partial string" then "hit enter" to get either a sole result or a selection window.

Keep in mind that the "type and hit enter" workflow functions as expected elsewhere in the application.
So while it's probably not "blocking" in the true sense of the term, it is a major UX discontinuity and definitely a regression.

**Comment by ehuelsmann** [comment] 2018-04-13 21:10
My point/question remains: "what does it block?" I mean, you've reiterated the fact that it blocks, but not what it blocks. Does it block a release? If so,  which one? We've released multiple releases without you objecting to the fact that those should be released without a fix for this issue.

BTW, neither `ENTER` nor `TAB` actually selects a value in the "Part Description" field for the invoice: the entered text (search text?) is left in the field as-is.

**Comment by sbts** [comment] 2018-04-14 02:13
I would like to say it should block any release.
It certainly should be fixed as soon as possible in 1.5 as it's a "broken UX" issue when compared with other UI's that people use.

Regardless of when it's fixed in 1.5 I'd say it definitely blocks 1.6

**Comment by ehuelsmann** [comment] 2018-04-14 07:15
While I do see your point that this is an annoyance at minimum and a risk when assessed more conservatively, I fail to see the relative priority. (Note that I'm unable to reproduce your `ENTER` and/or `TAB` behaviour where the wrong item is being selected in the *Description* field; so I don't really see the risk here either...)
I think we have bugs where functionality is actually broken (entry of single-day timecards comes to mind), but nothing is completely broken here.
I'd like to reserve the `blocking` tag for those cases where we absolutely can't release without a fix for the specific bug and/or feature. (Such as the schema upgrade feature for 1.6.)

**Comment by ehuelsmann** [comment] 2018-04-14 08:07
Hmm. thinking about it, I'm not sure I want to change the current behaviour: what if I entered a description which happens to match a substring of a part, but I want to use my own description? I'm seeing the search functionality on the description field as a shortcut for having to go through the Parts Search page.

**Comment by ehuelsmann** [comment] 2018-04-14 08:08
I'm removing "Regression" because it definitely isn't a regression in the sense that there never was "Tab behaviour" in any of the prior releases.

**Comment by sbts** [comment] 2018-04-14 10:26
Actually there was.
Tab would move on to the next field *without* altering the content of the current field.

The net result of that behavior was that....
On next update the content of the field would be used as a search term.

Current behavior mixes several idioms with none of them being obviously dominant. 

I'll need to retest with the latest codebase but I believe there are still a number of UX issues around this to be corrected.
Especially on slow links/browsers

**Comment by ehuelsmann** [comment] 2018-04-14 11:54
I'm not seeing the behaviour you describe. `TAB` (nor `ENTER`) updates the description field (at least not in my tests) and the behaviour I'm seeing hasn't changed since 1.5.0.

**Comment by ehuelsmann** [comment] 2020-01-05 20:34
Waiting for user feedback since May 2018. Closing.

Note: feel free to re-open, but please attach a screen recording when you do.

**Closed by ehuelsmann** 2020-01-05 20:34 UTC
Labels: waiting-for-user
