### ISSUE TITLE
Cash > Receipt accessed by name inconsistent with Cash > Vouchers > Receipts accessed by number

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2352] opened 2016-12-06 20:23 UTC
We access Cash > Receipt by name and Cash > Vouchers > Receipts or Cash > Vouchers > Reverse Receipts by numbers.
We should provide more consistency between screens and, possibly a user preference, to select which is preferred.

**Comment by ehuelsmann** [comment] 2020-09-13 21:14
Duplicate of #2436 .

**Closed by ehuelsmann** 2020-09-13 21:14 UTC
Labels: enhancement
