### ISSUE TITLE
Migrate data from ledger123 to ledgerSMB

### ISSUE THREAD

**Issue by kartalbas** [ledgersmb/LedgerSMB#7498] opened 2023-07-13 17:37 UTC
Hi all,

I hope to find an answer here over and I'm very thanksfull in advance for your effort and time to try to help me out.

As my title already shows, Im searching for an howto or an migration tool to migrate data from ledger123 (I assume currently it is the most compatible fork of sql-ledger) to ledgersmb. On ledger123 PostgreSQL I have my customers, suppliers, chart accouting table, financial accouting bookings data.

Thanks in advance
Mehmet

**Comment by ehuelsmann** [comment] 2023-07-14 14:05
Hi!

Thanks for stopping by and asking this question! Our code looks at the `defaults` table to identify SQL Ledger and LedgerSMB databases. If the `defaults` table contains a record with `fldname='version'`, it's recognized as SQL Ledger with the version `<fldvalue>`. If your database does the same thing, and the schema is the same as in SQL Ledger, chances are migration will be re-usable for the most part.

Which version does your database list in the defaults table?

Regards,


Erik.

**Comment by kartalbas** [comment] 2023-07-14 17:31
Hi Erik,

thanks a lot for your fast feedback! Sounds not bad at first attempt ;-)

Regarding your question:

the sql dump shows the beginning:

```
--
-- Data for Name: defaults; Type: TABLE DATA; Schema: public; Owner: sql-ledger
--

COPY public.defaults (fldname, fldvalue) FROM stdin;
version	2.8.12
.
.
.
```

I exported from ledger123 "Community Version 2.8.33" with PostgreSQL 9.6 with command
`pg_dump --host=localhost --username=postgres --password --dbname=xxxxxdb > xxxxxdb.sql
`

**Comment by ehuelsmann** [comment] 2023-07-14 18:46
@kartalbas Thanks for that dump. It allowed me to assess what may or may not be a problem for your migration. Your version being post-2.8.3, it has a bit of a different concept of multi-currency aspects than early LedgerSMB versions (pre-1.7). Are you using a single currency? If so, this difference is of no consequence. If you're using multiple currencies, it *is* of importance.

Initial conclusion: your database will be recognized as "SQL Ledger" and the version it will be recognized as, is 2.8.33. So that part is good.

If you run into issues migrating, let us know and we'll help you get migrated.

**Comment by kartalbas** [comment] 2023-07-14 19:54
hi @ehuelsmann,
thanks a lot, what I did, with psql
- I create the role
- the database 
- that import the dump
- navigated to setup.pl in browser
- selected postgres, password and database => login OK
- screen it shows as you already told, it recognizde :): 
      Confirm Operation
      SQL-Ledger database detected.
      Would you like to migrate the database?
      => I press YES
- screen: 
       GIFI accounts not in "gifi" table
       Please add the missing GIFI accounts
       => I filled some description for GIFI accounts which was missing, pressed Save and Retry
       
ended with:
Error!
Upgrade query affected 0E0 rows while a single row was expected at lib/LedgerSMB/Upgrade_Tests.pm line 304.

dbversion: 1.10.19, company:

**Comment by ehuelsmann** [comment] 2023-07-14 21:41
> Error!
> Upgrade query affected 0E0 rows while a single row was expected at lib/LedgerSMB/Upgrade_Tests.pm line 304.

You found a bug. The problem is that the data is processed by an UPDATE statement, but since it's missing data, it should have been processed with an INSERT statement...

The fix is in the PR I've issued. (#7499 above). Do you use the Docker images? Or do you run your own installation? It'll be easy either way to locally apply the fix, but instructions differ. (I'll publish a new version with the fixes, but it's rather cumbersome for you to have to wait for me to publish a new version before you can continue your import.)

**Comment by kartalbas** [comment] 2023-07-15 08:43
thank you @ehuelsmann for the fast fix! Im using the docker, I will patch locally and docker commit, later with a new version I will update my image. Im going to try the fix :-)

**Comment by kartalbas** [comment] 2023-07-15 09:13
> > Error!
> > Upgrade query affected 0E0 rows while a single row was expected at lib/LedgerSMB/Upgrade_Tests.pm line 304.
> 
> You found a bug. The problem is that the data is processed by an UPDATE statement, but since it's missing data, it should have been processed with an INSERT statement...
> 
> The fix is in the PR I've issued. (#7499 above). Do you use the Docker images? Or do you run your own installation? It'll be easy either way to locally apply the fix, but instructions differ. (I'll publish a new version with the fixes, but it's rather cumbersome for you to have to wait for me to publish a new version before you can continue your import.)

hi @ehuelsmann I just replaced the file in docker exactly with yours, but i got the same error again:

```
Error!
Upgrade query affected 0E0 rows while a single row was expected at lib/LedgerSMB/Upgrade_Tests.pm line 304.

dbversion: 1.10.19, company:

```
looking in docker the patch, it exists:

```
root@32523d0ce32a:/srv/ledgersmb/lib/LedgerSMB# cat Upgrade_Tests.pm | grep -in "       insert => 1," -A7 -B12
629-push @tests, __PACKAGE__->new(
630-   test_query => q{select distinct gifi_accno as accno from chart
631-                   where not exists (select 1
632-                                       from gifi
633-                                      where gifi.accno = chart.gifi_accno)
634-                         and gifi_accno is not null
635-                         and charttype <> 'H'
636-                         and gifi_accno !~ '^\s*$'},
637- display_name => marktext('GIFI accounts not in "gifi" table'),
638-         name => 'missing_gifi_table_rows',
639- display_cols => [ 'accno', 'description' ],
640-        table => 'gifi',
641:       insert => 1,
642-      columns => ['description'],
643-   id_columns => ['accno'],
644- instructions => marktext('Please add the missing GIFI accounts'),
645-      appname => 'sql-ledger',
646-  min_version => '2.7',
647-  max_version => '3.0'
648-);
```

**Comment by kartalbas** [comment] 2023-07-15 11:12
hi @ehuelsmann, you show me the correct direction already, thank you. I made a lot of adaptions directly on my db, wherever a unique problem appears. At the and I had to give the default country, AR and AP, but after that it takes a while and shows me following error:

Error!
Failed to create upgrade instructions to be sent to 'psql': file error - sl2.8.sql: not found at lib/LedgerSMB/Database/Upgrade.pm line 280.

dbversion: 1.10.19, company:

**Comment by kartalbas** [comment] 2023-07-15 12:07
hi @ehuelsmann, I already move forward and get following error

UI:
```
Error!
error running file '/tmp/WjLfaP7Tzv'; (command: 'psql' '--set=ON_ERROR_STOP=on' '-f' '/tmp/WjLfaP7Tzv'): exited with code 3 at lib/LedgerSMB/Database/Upgrade.pm line 290.

```
dbversion: 1.10.19, company:

psql output:
```
root@32523d0ce32a:/tmp# cat dblog_2023-07-15T120326_10_stderr
psql:/tmp/WjLfaP7Tzv:20: NOTICE:  column "lsmb_entry_id" of relation "acc_trans" does not exist, skipping
psql:/tmp/WjLfaP7Tzv:480: ERROR:  new row for relation "entity_credit_account" violates check constraint "entity_credit_account_req_curr"
DETAIL:  Failing row contains (1, 31, 1, null, null, null, 0, null, f, 0, 0, 6, null, en, null, null, 2011-01-01, null, 0, null, null, 143, 52, null, null).

```

**Comment by ehuelsmann** [comment] 2023-07-15 15:07
> I assume this is a multi currency problem as you already mentioned in the beginngin... damn..

Ah! Not so fast! The `vendor` and `customer` tables in SQL-Ledger have a `curr` field. LedgerSMB's upgrade is trying to copy that field (which must not be NULL) into our `entity_credit_account` table's `curr` field. In our database, the `curr` value is a 3-letter currency code which must existing the `currency` table. Maybe SQL Ledger allows NULL values or uses a different value than the 3-letter code (maybe an integer linking into another table?)

**Comment by ehuelsmann** [comment] 2023-07-15 15:08
> hi @ehuelsmann, you show me the correct direction already, thank you. I made a lot of adaptions directly on my db, wherever a unique problem appears. At the and I had to give the default country, AR and AP, but after that it takes a while and shows me following error:

Hi! Do you have a list of all the things you needed to change? I'd like to write checks for those so we can help future people migrate more easily.

**Comment by kartalbas** [comment] 2023-07-15 16:56
> > I assume this is a multi currency problem as you already mentioned in the beginngin... damn..
> 
> Ah! Not so fast! The `vendor` and `customer` tables in SQL-Ledger have a `curr` field. LedgerSMB's upgrade is trying to copy that field (which must not be NULL) into our `entity_credit_account` table's `curr` field. In our database, the `curr` value is a 3-letter currency code which must existing the `currency` table. Maybe SQL Ledger allows NULL values or uses a different value than the 3-letter code (maybe an integer linking into another table?)

thank you, I checked but the curr is not empty and not null in tables vendor and customer  - and - they are existing in table curr.

```
simetrixdb=# select * from curr;
 rn | curr | precision
----+------+-----------
  1 | CHF  |         2
  2 | EUR  |         2
  3 | USD  |         2
(3 rows)

simetrixdb=# select distinct curr from customer;
 curr
------
 CHF
 EUR
(2 rows)

simetrixdb=# select distinct curr from vendor;
 curr
------
 CHF
 EUR
 USD
(3 rows)

```

still same error
```
root@0190867f1cad:/tmp# cat dblog_2023-07-15T165555_9_stderr
psql:/tmp/33mwahFpGu:20: NOTICE:  column "lsmb_entry_id" of relation "acc_trans" does not exist, skipping
psql:/tmp/33mwahFpGu:480: ERROR:  new row for relation "entity_credit_account" violates check constraint "entity_credit_account_req_curr"
DETAIL:  Failing row contains (1, 31, 1, null, null, null, 0, null, f, 0, 0, 6, null, en, null, null, 2011-01-01, null, 0, null, null, 143, 52, null, null)

```

**Comment by kartalbas** [comment] 2023-07-15 16:58
> > hi @ehuelsmann, you show me the correct direction already, thank you. I made a lot of adaptions directly on my db, wherever a unique problem appears. At the and I had to give the default country, AR and AP, but after that it takes a while and shows me following error:
> 
> Hi! Do you have a list of all the things you needed to change? I'd like to write checks for those so we can help future people migrate more easily.

Hi @ehuelsmann, until now it was only data improvements which was given out during migration wizard, but I didn't used the table, I directly modifed the data in the database and restart the migration. So until the wizard navigate me, nothing to add from my site.

**Comment by ehuelsmann** [comment] 2023-07-15 17:45
> thank you, I checked but the curr is not empty and not null in tables vendor and customer - and - they are existing in table curr.

I checked the version of the file on 1.10 and the one on master. The latter has had a commit from @ylavoie last month with respect to currencies. Especially: it moved populating the currencies table all the way to the beginning of the migration process where it is almost completely at the end in the 1.10 file. I think that explains your problem.

Please try replacing `sql/upgrade/sl3.0.sql` (which you now named `sl2.8.sql`, I think) with the one found here: https://github.com/ledgersmb/LedgerSMB/blob/master/sql/upgrade/sl3.0.sql

**Comment by kartalbas** [comment] 2023-07-15 18:03
> > thank you, I checked but the curr is not empty and not null in tables vendor and customer - and - they are existing in table curr.
> 
> I checked the version of the file on 1.10 and the one on master. The latter has had a commit from @ylavoie last month with respect to currencies. Especially: it moved populating the currencies table all the way to the beginning of the migration process where it is almost completely at the end in the 1.10 file. I think that explains your problem.
> 
> Please try replacing `sql/upgrade/sl3.0.sql` (which you now named `sl2.8.sql`, I think) with the one found here: https://github.com/ledgersmb/LedgerSMB/blob/master/sql/upgrade/sl3.0.sql

thank you, I replace and give a try, error messages changed!

```
UI:
Error!
error running file '/tmp/mkvxcvEXSn'; (command: 'psql' '--set=ON_ERROR_STOP=on' '-f' '/tmp/mkvxcvEXSn'): exited with code 3 at lib/LedgerSMB/Database/Upgrade.pm line 290.

dbversion: 1.10.19, company:

SQL:
root@ubuntu-4gb-nbg1-1:~/ledgersmb-docker# docker exec -u root -it 0190867f1cad cat /tmp/dblog_2023-07-15T180206_11_stderr
psql:/tmp/mkvxcvEXSn:1: error: invalid command \",
root@ubuntu-4gb-nbg1-1:~/ledgersmb-docker#
```

**Comment by ehuelsmann** [comment] 2023-07-15 18:39
I looked all over, but I don't understand what the error can be. does the file /tmp/mkvxcvEXSn still exist? I'd be interested to see what's on line 1.

**Comment by kartalbas** [comment] 2023-07-15 18:48
> I looked all over, but I don't understand what the error can be. does the file /tmp/mkvxcvEXSn still exist? I'd be interested to see what's on line 1.

unfortunately not :( see below:
```
root@ubuntu-4gb-nbg1-1:~/ledgersmb-docker# docker exec -u root -it 0190867f1cad ls -ltr /tmp
total 40
-rw-r--r-- 1 root     root     1623 Jun 23 21:57 derived-deps
drwxr-xr-x 3 www-data www-data 4096 Jul 15 14:27 lsmb_templates
-rw-r--r-- 1 www-data www-data  137 Jul 15 16:16 ledgersmb.conf
-rw------- 1 www-data www-data 3173 Jul 15 16:55 dblog_2023-07-15T165555_9_stdout
-rw------- 1 www-data www-data  401 Jul 15 16:55 dblog_2023-07-15T165555_9_stderr
-rw------- 1 www-data www-data 3173 Jul 15 17:58 dblog_2023-07-15T175848_9_stdout
-rw------- 1 www-data www-data  401 Jul 15 17:58 dblog_2023-07-15T175848_9_stderr
-rw------- 1 www-data www-data 3173 Jul 15 17:59 dblog_2023-07-15T175911_9_stdout
-rw------- 1 www-data www-data  406 Jul 15 17:59 dblog_2023-07-15T175911_9_stderr
-rw------- 1 www-data www-data    0 Jul 15 18:02 dblog_2023-07-15T180206_11_stdout
-rw------- 1 www-data www-data   51 Jul 15 18:02 dblog_2023-07-15T180206_11_stderr
root@ubuntu-4gb-nbg1-1:~/ledgersmb-docker#
```

another appraoch: for me is very important to have the chart and gifi tables, since the year is closed and I don't have any data for 2023, I can begin with a new database - but with my former chart and gifi tables. To have this, I go the way to delete all data except chart, gifi and default. During migration I get following error:

```
AR account available when customers defined
When customers are defined, an AR account must be defined, however, your setup doesn't. Please go back and define one.
```

https://github.com/ledgersmb/LedgerSMB/assets/5513005/a0775fe7-110f-4eda-b8f5-56a8b224e79d

**Comment by ehuelsmann** [comment] 2023-07-15 19:23
if you want to start with a new GIFI and Chart table, I think it's faster to send me a CSV dump of your chart and gifi tables. I'll create 2 csvs for you which you can import after creating a new database. mail me privately at erik at efficito dot com.

if you want me to help you migrate the old data (be it to a "dead" database or to continue working in the current database), please mail me too. I think I can help and make the transition smoother. What I learn from the exercise I contribute back to the project.

**Comment by kartalbas** [comment] 2023-07-15 19:36
> 

thank you @ehuelsmann , the mail is already out.

**Comment by ehuelsmann** [comment] 2023-07-16 14:48
For the record: the rest of the help was provided through private conversation.

Conclusion: the migration from SL2.8 and Ledger123 needs more work. There was not done significant work in private to contribute anything back to the public repository, except for fixing importing UTF-8 text CSVs.

**Closed by ehuelsmann** 2023-07-16 14:48 UTC
