### ISSUE TITLE
Changing the "To" field in invoice emails results in no mail sent

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#6052] opened 2021-09-28 23:38 UTC
When testing emailing an invoice, my AR person changed the "To" address to me instead of the customer. When he sent it, it saved and nothing else happened -- no email was actually sent. (Other successful mail shows up in our mail logs -- this one is not).

**Comment by freelock** [comment] 2021-09-28 23:40
I'm not entirely sure which button he pressed at the bottom of the mail -- and it's not clear exactly when this mail was generated. Perhaps we can add some more metadata to the email screen after it has been sent?

e.g. current state, timestamp when it was sent, button to trigger next workflow state if it's not complete?

**Comment by ehuelsmann** [comment] 2021-09-29 10:20
The problem is broader: no e-mail was getting sent at all. that's now fixed (a state in the state machine was skipped).

**Closed** 2021-09-29 11:57 UTC
