### ISSUE TITLE
Cannot print invoice

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1214] opened 2016-01-05 07:23 UTC
On 1.5-beta3:

* AR -> Search, Continue.
* Open an existing invoice (data migrated from 1.4).
* Click "Print" (dropdowns set to HTML, Screen)

Get the following error:

'Attribute (language_code) does not pass the type constraint because: Validation failed for 'Str' with value undef at constructor LedgerSMB::Template::DB::new (defined at LedgerSMB/Template/DB.pm line 172) line 75
LedgerSMB::Template::DB::new('LedgerSMB::Template::DB', 'HASH(0xae1b000)') called at LedgerSMB/Template/DB.pm line 72
LedgerSMB::Template::DB::get_template('LedgerSMB::Template::DB', 'invoice', undef, 'html') called at LedgerSMB/Template/HTML.pm line 139
LedgerSMB::Template::HTML::process('LedgerSMB::Template=HASH(0xa9ea538)', 'HASH(0xac07df8)') called at LedgerSMB/Template.pm line 356
LedgerSMB::Template::render('LedgerSMB::Template=HASH(0xa9ea538)', 'Form=HASH(0x47e2b90)') called at bin/io.pl line 1996
lsmb_legacy::print_form(undef) called at bin/io.pl line 1559
lsmb_legacy::print at bin/old-handler.pl line 177
lsmb_legacy::try {...} at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 92
eval {...} at /usr/local/lib/perl5/site_perl/5.22.1/Try/Tiny.pm line 83
Try::Tiny::try('CODE(0xa86b1f0)', 'Try::Tiny::Catch=REF(0xa8bedf8)') called at bin/old-handler.pl line 193
require bin/old-handler.pl at LedgerSMB/PSGI.pm line 71
LedgerSMB::PSGI::_run_old('is.pl') called at LedgerSMB/PSGI.pm line 50
LedgerSMB::PSGI::__ANON__ at /usr/share/perl5/CGI/Emulate/PSGI.pm line 29
CGI::Emulate::PSGI::__ANON__('HASH(0x7d06d20)') called at /usr/share/perl5/Plack/Middleware/Static.pm line 18
Plack::Middleware::Static::call('Plack::Middleware::Static=HASH(0x7bfc880)', 'HASH(0x7d06d20)') called at /usr/share/perl5/Plack/Component.pm line 50
Plack::Component::__ANON__('HASH(0x7d06d20)') called at /usr/share/perl5/Plack/Util.pm line 142
eval {...} at /usr/share/perl5/Plack/Util.pm line 142
Plack::Util::run_app('CODE(0x7bfc808)', 'HASH(0x7d06d20)') called at /usr/share/perl5/Starman/Server.pm line 281
Starman::Server::process_request('Starman::Server=HASH(0x1d6b348)', 'Net::Server::Proto::TCP=GLOB(0x8854a10)') called at /usr/share/perl5/Net/Server.pm line 74
Net::Server::run_client_connection('Starman::Server=HASH(0x1d6b348)') called at /usr/share/perl5/Net/Server/PreFork.pm line 229
eval {...} at /usr/share/perl5/Net/Server/PreFork.pm line 229
Net::Server::PreFork::run_child('Starman::Server=HASH(0x1d6b348)') called at /usr/share/perl5/Net/Server/PreFork.pm line 187
Net::Server::PreFork::run_n_children('Starman::Server=HASH(0x1d6b348)', 5) called at /usr/share/perl5/Net/Server/PreFork.pm line 111
Net::Server::PreFork::loop('Starman::Server=HASH(0x1d6b348)') called at /usr/share/perl5/Net/Server.pm line 60
Net::Server::run('Starman::Server=HASH(0x1d6b348)', 'port', 'ARRAY(0x2149838)', 'host', '*', 'proto', 'tcp', 'serialize', 'none', 'min_servers', 5, 'min_spare_servers', 4, 'max_spare_servers', 4, 'max_servers', 5, 'max_requests', 1000, 'user', 0, 'group', '0 0 0', 'listen', 1024, 'check_for_waiting', 1, 'no_client_stdout', 1) called at /usr/share/perl5/Starman/Server.pm line 89
Starman::Server::run('Starman::Server=HASH(0x1d6b348)', 'CODE(0x1d6b2a0)', 'HASH(0x1d6b540)') called at /usr/share/perl5/Plack/Handler/Starman.pm line 18
Plack::Handler::Starman::run('Plack::Handler::Starman=HASH(0x1d6b288)', 'CODE(0x1d6b2a0)') called at /usr/share/perl5/Plack/Loader/Delayed.pm line 20
Plack::Loader::Delayed::run('Plack::Loader::Delayed=HASH(0x1c7f410)', 'Plack::Handler::Starman=HASH(0x1d6b288)') called at /usr/share/perl5/Plack/Runner.pm line 277
Plack::Runner::run('Plack::Runner=HASH(0x1c86fe0)') called at /usr/bin/starman line 38
'

**Comment by ehuelsmann** [comment] 2016-05-19 19:00
This must have been among the many 1.5 invoice (printing) fixes, because I cannot reproduce anymore. Closing as fixed.

**Closed by ehuelsmann** 2016-05-19 19:00 UTC
