### ISSUE TITLE
Feature request: Make logo (and other images) available to templates

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1934] opened 2016-07-31 17:22 UTC
From https://vector.im/develop/#/room/!qyoLumPqusaXqFJNyK:matrix.org/$14699851611738zqvmo:matrix.freelock.com

... provide the ability to have a "company logo" available to insert into invoice/other templates. Possibly a mechanism/practice for loading images from products, personnel, arbitrary image asset library in template system?

**Comment by einhverfr** [comment] 2016-07-31 17:43
duplicate of #1816

**Closed by einhverfr** 2016-07-31 17:43 UTC
