### ISSUE TITLE
Transaction disappeared when saving AR/AP transaction

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5452] opened 2021-05-24 10:10 UTC
The transactions are disappeared when saving AR/AP transaction. This is urgent and need to fix ASAP.
You can view screen recording at below link

https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/mXGmczkiZCJMkpRwksbAWwhz

**Comment by ehuelsmann** [comment] 2021-05-24 19:58
I've found the reason, but not the cause:

When you remove the "AP_overpayment" checkmark from these accounts, it starts working.

**Comment by ehuelsmann** [comment] 2021-05-24 21:16
The cause has been identified to be https://github.com/ledgersmb/LedgerSMB/blob/d87c4f8/old/lib/LedgerSMB/Form.pm#L1954-L1969

This bit of code precludes AP accounts used in the account dropdown for transactions to be marked with anything but "AP_amount" flags (account links).

**Comment by ehuelsmann** [comment] 2021-08-21 12:11
I'm not sure what the next step should be here.

**Comment by ehuelsmann** [comment] 2021-08-21 12:11
Can we close this?

**Closed** 2021-11-19 12:41 UTC
Labels: worksforme, waiting-for-user
