### ISSUE TITLE
Is there a problem starting setup.pl on 1.12-dev ?

### ISSUE THREAD

**Issue by howardlowndes** [ledgersmb/LedgerSMB#7828] opened 2023-12-16 01:05 UTC
### Version

1.12=dev

### What browsers are you seeing the problem on?

Other

### What happened?

Chromium browser (not in dropdown list).

I;ve just downloaded LedgerSMB-master.zip, extracted it (as root) to /opt/LedgerSMB-master_20231216T0653, then soft linked that (as root) to /opt/ledgersmb - this to preserve the earier version 1.11.4. I then restarted the starman service. That service restarted OK but did gove the following warning message:

`● ledgersmb-starman.service - LedgerSMB Starman
     Loaded: loaded (/etc/systemd/system/ledgersmb-starman.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-12-16 11:07:59 AEDT; 11s ago
   Main PID: 11467 (/opt/LedgerSMB-)
      Tasks: 1 (limit: 4915)
        CPU: 11.552s
     CGroup: /system.slice/ledgersmb-starman.service
             └─11467 /opt/LedgerSMB-master_20231216T0653/bin/ledgersmb-server.psgi

Dec 16 11:08:06 raspi-office starman[11467]:     it cannot do this, so it also tells you what operation you used the
Dec 16 11:08:06 raspi-office starman[11467]:     undefined value in.  Note, however, that perl optimizes your program
Dec 16 11:08:06 raspi-office starman[11467]:     and the operation displayed in the warning may not necessarily appear
Dec 16 11:08:06 raspi-office starman[11467]:     literally in your program.  For example, "that $foo" is usually
Dec 16 11:08:06 raspi-office starman[11467]:     optimized into "that " . $foo, and the warning will refer to the
Dec 16 11:08:06 raspi-office starman[11467]:     concatenation (.) operator, even though there is no . in
Dec 16 11:08:06 raspi-office starman[11467]:     your program.
Dec 16 11:08:06 raspi-office starman[11467]:     
Dec 16 11:08:06 raspi-office starman[11467]: Use of uninitialized value in subroutine entry at
Dec 16 11:08:06 raspi-office starman[11467]:         /usr/lib/arm-linux-gnueabihf/perl-base/File/Spec/Unix.pm line 280, <DATA> line 1 (#1)`

I then called localhost:5672/setup.pl and got a login screen (of sorts). I allows me to input the fields, but it won't let me log in, it just flashes and returns. In the top left corner of the window is the line:

`<%= htmlWebpackPlugin.tags.headTags %> ${htmlWebpackPlugin.tags.bodyTags}`

and just above the main logo are three recurrent cycling vertical bars, and below the logo is the version 1.12-dev .

The source code of the login page is here::

`
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <link rel="shortcut icon" href="[favicon.ico](http://localhost:5762/favicon.ico)" type="image/x-icon" />    <%= htmlWebpackPlugin.tags.headTags %>
    <link href="[js/dojo/resources/dojo.css](http://localhost:5762/js/dojo/resources/dojo.css)" rel="stylesheet">
    <link href="[js/css/claro.css](http://localhost:5762/js/css/claro.css)" rel="stylesheet">
    <link href="[js/css/ledgersmb.css](http://localhost:5762/js/css/ledgersmb.css)" rel="stylesheet">
    <link href="[js/css/system/setup.css](http://localhost:5762/js/css/system/setup.css)" rel="stylesheet">
    <script>
        var dojoConfig = {
            async: 1,
            parseOnLoad: false,
            locale: "en",
            packages: [{"name":"lsmb","location":"../lsmb"}],
            mode: "<%= htmlWebpackPlugin.options.mode %>"
        };
        var lsmbConfig = {
            language: "en",
            
            version: "1.12.0-dev"
        };
    </script>
    ${htmlWebpackPlugin.tags.bodyTags}
    <meta name="robots" content="noindex,nofollow" />
</head>
<body id="setup-login" class="lsmb claro">
  <div style="width:100%;height:100%">
    <div>
        <div class="setupconsole">
            <div id="loading">
                <img style="display: block; margin: auto auto;"
                    src="[js/dijit/icons/images/loadingAnimation.gif](http://localhost:5762/js/dijit/icons/images/loadingAnimation.gif)"
                    alt="If this text is showing, there's most likely a problem with the Dojo setup"
                    title="Loading ..."
                    width="20" height="20" />
            </div>
            <div id="logindiv">
                <div class="login" align="center">
                    <a href="http://www.ledgersmb.org/"
                    target="_top">
                    <img src="[images/ledgersmb.png](http://localhost:5762/images/ledgersmb.png)"
                            class="logo"
                            alt="LedgerSMB Logo" />
                    </a>
                    <h2 align="center" style="margin-top: 0">
                        1.12.0-dev
                    </h2>
                    <div class="listtop">
                        Database administrator credentials
                    </div>
                </div>
                <form id="loginform"
                      name="credentials"
                      style="margin-top:1em">
                  <div class="login_form">
                    <label  id="s-user-label"  for="s-user"  class="username" >DB admin login</label><span><select id="s-user" class="username" title="DB admin login" name="s_user" data-dojo-type="dijit/form/ComboBox" data-dojo-props="value:'', placeHolder:'Select or Enter User'" tabindex="1" autocomplete="off" ><option id="s-user-1" value="lsmb_dbadmin" >lsmb_dbadmin</option><option id="s-user-2" value="postgres" >postgres</option></select></span><label  id="s-password-label"  for="s-password"  class="password" >Password</label><span><input id="s-password" class="password" title="Password" type="password" name="s_password" size="15" data-dojo-type="dijit/form/ValidationTextBox" tabindex="2" autocomplete="off" /></span><label  id="database-label"  for="database"  class="database" >Database</label><span><input id="database" class="database" title="Database" type="text" name="database" size="15" data-dojo-type="dijit/form/ValidationTextBox" tabindex="3" maxlength="255" /></span>
                  </div>
                  <div class="inputrow"
                       style="text-align:right; padding-right: 4ex; margin-top: 1ex">
                    <button data-dojo-type="lsmb/SetupLoginButton"
                            class="submit"
                            data-dojo-props="action:'login'"
                            tabindex="4"
                            >Login</button>
                    <button data-dojo-type="lsmb/SetupLoginButton"
                            class="submit"
                            data-dojo-props="action:'create_db'"
                            tabindex="5"
                            >Create</button>
                  </div>
                </form>
            </div>
        </div>
    </div>
  </div>
</body>

</html>`

### What should have happened?

Am I doing this all wrong?

**Comment by howardlowndes** [comment] 2023-12-16 02:21
Copying ./doc/conf/ledgersmb.yaml to ./ledgersmb.yaml resolve the warning message when restarting the ledgersmb.starman service, but didn't resolve the main problem.

**Comment by ehuelsmann** [comment] 2023-12-16 08:43
This is expected behaviour: those are created by GitHub , meaning they are a snapshot of what is in the repository at this time. Our releases are something entirely different: those include processed and prepared files. We made that choice to prevent having to include a full asset compilation pipeline as some projects do (like GitLab and other Ruby projects), since the outcome is the same everytime.

You can run the development version by following these instructions: https://github.com/ledgersmb/ledgersmb-dev-docker?tab=readme-ov-file#ledgersmb-docker-development--testing-infrastructure which include building the missing javascript components.

**Comment by howardlowndes** [comment] 2023-12-16 11:19
It is confusing because a naive user might tend towards the "master" rather
than the latest production release.

**Comment by ehuelsmann** [comment] 2023-12-19 05:29
If this is one of the issues which keeps the naive user from using the master branch in a production setting then that is probably a good thing: although we strive to keep matter stable, there is a lot of change going on in the software which could be destabilizing. Before we release a new minor version, additional testing is done by early adapters (who know what they are doing) in production situations to iron out the most important issues that didn't get caught during development.

**Comment by ehuelsmann** [comment] 2023-12-19 05:31
With the above comment, this question is probably answered. Closing. Feel free to reopen if not.

**Closed by ehuelsmann** 2023-12-19 05:31 UTC
Labels: type:question
