### ISSUE TITLE
1.5 breaks barcode scanning

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#1584] opened 2016-05-21 17:24 UTC
In previous versions, you could enter multiple items in a row with simply the sku and <Enter> keys. I know this was done to support bar-code readers, which act as a keyboard entering the string in the barcode followed by enter.

Before, when you enter a sku and press Enter, the form refreshed with the line item added, and the cursor focused on the SKU field of the next (new) line item).

Now when you do this, the parts selector does not fire. The sku and line item is added and set to read-only, with no other fields filled in, and no new line item created for the next part.

**Comment by einhverfr** [comment] 2017-07-02 11:30
duplicate of #1346

**Comment by ehuelsmann** [comment] 2023-01-08 13:04
#7070 fixes the data being filled in and the move to the next data entry row. It does *not* fix the barcode lookup.

**Comment by ehuelsmann** [comment] 2023-01-08 22:37
Changing topic of the issue to indicate that the only remaining issue here - if anything - is that the barcode being scanned isn't being matched.

**Closed** 2023-04-15 18:34 UTC
Labels: regression, new-ui
