### ISSUE TITLE
Transaction payment posted against 'wrong' account

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#3956] opened 2018-12-29 16:28 UTC
* AP->Add Transaction
* Enter Invoice Details
* Enter Payment from "Account 1"
* Click "Save"
* Realise wrong payment account was selected - change to "Account 2"
* Click Update
* Note that payment account remains selected to "Account 2"
* Click Post

As a user, I expect the payment to be recorded as it appears when I click Post - in this case against "Account 2".

In fact, the payment was recorded against "Account 1" - different to how the transaction was displayed on screen after "Update". Nasty surprise!

Tested in 1.6 and master.

**Comment by ehuelsmann** [comment] 2020-01-12 12:42
duplicate of #975

**Closed by ehuelsmann** 2020-01-12 12:42 UTC
