### ISSUE TITLE
Entity type "Robot" can't be a user even though it should be

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#5033] opened 2020-09-13 14:31 UTC
Currently, a "Robot" entity type can't be configured as a "user".
This doesn't seem to be sensible as a robot would normally need to be able to login and interact with LSMB in some way.

Without being a "user" there is no way (from the UI) to manage the database role or password that is needed to login to the database

**Comment by ehuelsmann** [comment] 2020-09-13 14:33
Duplicate of #1688.

**Closed by ehuelsmann** 2020-09-13 14:33 UTC
