### ISSUE TITLE
Show status for save/update/delete action to get better UX

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#4833] opened 2020-07-28 08:19 UTC
![image](https://user-images.githubusercontent.com/31498748/88638367-6c373d80-d0e1-11ea-9599-c87ec25f0328.png)

**Comment by ehuelsmann** [comment] 2020-12-15 07:35
Duplicate of #1879

**Closed by ehuelsmann** 2020-12-15 07:35 UTC
