### ISSUE TITLE
Balance Sheet out of balance

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#3241] opened 2017-10-11 18:30 UTC
I hit something strange in my books trying to generate a balance sheet -- the Assets do not equal Liabilities + Equity. This is only for certain dates (in my books, between sometime in October 2016 and January 28, 2017). The amount is tiny -- ranging from 0.94 to 1.90.

Based on the amount and timing, this seems to be related to some voided transactions that include sales tax. When I look at the chart for the sales tax account, I see voided invoices on 10/11 with tax debits of 0.96 and 0.95. (There is also one for $15.56 but for some reason this amount does not seem to have affected the balance).

When the liability was paid, on 2017-01-31, the balance sheet went back to balanced.

The other possibility here is that there are a few transactions that the client paid the subtotal but neglected to pay the sales tax (due to a different issue we resolved already). I received the missing amount into a "Bad debts" account, a contra - income account on 2017-12-31. However, these amounts do not reflect the difference in the balance, so I'm thinking it's more likely something to do with voids.

**Comment by ehuelsmann** [comment] 2017-11-12 11:59
It's troubling to see that you were able to get your balance out of balance. However, without further data, we can't really help you. Can we get an anonymized copy of the database so I can analyse what could be the cause?
If not, I think we'll need to close the issue as it's not actionable for us right now.

**Comment by ehuelsmann** [comment] 2017-12-17 10:23
Closing due to inactivity.

**Closed by ehuelsmann** 2017-12-17 10:23 UTC
Labels: waiting-for-user
