### ISSUE TITLE
Missing templates for income statement & balance sheet

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1114] opened 2015-12-04 14:31 UTC
In the menu System -> Templates, the templates for the income statement and balance sheet are missing.

**Comment by ehuelsmann** [comment] 2015-12-04 14:32
Probably due to the fact that the template sources are located in UI/Reports/ ; probably the wrong place to store these...

**Comment by einhverfr** [comment] 2016-08-10 06:27
duplicate of #811

**Closed by einhverfr** 2016-08-10 06:27 UTC
Labels: bite-sized, duplicate, enhancement, Major Enhancement
