### ISSUE TITLE
Cannnot save account without heading

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1052] opened 2015-11-15 10:39 UTC
Via email

When trying to create an account and selecting a header was getting access denied (this is fixed for 1.4.19).

When not selecting a header got invalid syntax for integer '--'

**Comment by ehuelsmann** [comment] 2015-11-15 18:57
Hi Chris,

On second thought: should we want to support adding an account without an explicitly selected chart? I mean, the server will select a heading for the account, which results in possibly unexpected behaviour.

Regards,

Erik.
PS: Along the same lines, should we remove the automatic selection of a heading and instead change the COA files to have explicit ones?

**Comment by ehuelsmann** [comment] 2015-11-15 20:50
Agreed on blocking, but this doesn't result in incorrect bookkeeping (which is what 'bug:accounting' means to me). So, prefer to remove that.

**Comment by einhverfr** [comment] 2015-11-17 15:03
Currently null has a special meaning here, namely select according to old behavior.  We can rethink this for 1.5 I think but should probably fix for 1.4 at least (IMO).

**Comment by ehuelsmann** [comment] 2015-11-17 22:23
Ok. Resolving this for 1.4 by ensuring the old behaviour (and changing the
1.5 behaviour to disallow adding accounts without a heading) works for me.

**Closed** 2015-11-19 17:01 UTC
Labels: blocking
